### ISSUE TITLE
Suggestion: change file format?

### ISSUE THREAD

**Issue by AntimatterReactor** [startrekdude/resub#1]
I think because of the file format of .re, github thinks that the resub files are [c++](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L695), which causes some confusion.

Perhaps you should change it to something like .resb or .sub files since those file format isn't in lingust/language yaml.

NOTE: See https://stackoverflow.com/questions/5318580/how-does-github-figure-out-a-projects-language

**Comment by AntimatterReactor** [comment]
btw, nice conlang

**Comment by startrekdude** [comment]
I've followed the directions of [https://stackoverflow.com/a/43520676](https://stackoverflow.com/a/43520676) to hopefully fix it, we'll see when GitHub decides to re-run its language checker thingy.

Since when did C++ use .re anyways?

**Comment by AntimatterReactor** [comment]
> I've followed the directions of https://stackoverflow.com/a/43520676 to hopefully fix it, we'll see when GitHub decides to re-run its language checker thingy.

I think it worked

> Since when did C++ use .re anyways?

Idk, I've never heard about it either.
